/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import ScrollReveal from "@/components/ui/ScrollReveal";
import TextAnimation from "@/components/ui/TextAnimation";
import Button from "@/components/ui/Button";

const primaryButton = {
  text: "Book Your Spot",
  href: "https://bookings.vibefam.com/dreamsyogastudio/classes?"
};
const secondaryButton = {
  text: "Call Us",
  href: "tel:555-0123"
};

const ContactInline = () => {
  return (
    <section aria-label="Contact section" className="py-20 bg-background text-foreground">
      <div className="w-content-width mx-auto">
        <ScrollReveal variant="fade">
          <div className="text-center max-w-2xl mx-auto mb-12">
            <div className="px-3 py-1 mb-3 text-sm card rounded w-fit mx-auto">
              <p>Visit Our Studio</p>
            </div>
            <TextAnimation
              text="Location & Hours"
              variant="slide-up"
              gradientText={false}
              tag="h2"
              className="text-4xl md:text-5xl font-bold tracking-tight text-foreground"
            />
            <p className="mt-3 text-accent text-base md:text-lg">
              Experience personalized styling and premium hair care in our serene downtown studio.
            </p>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-stretch">
            <div className="lg:col-span-5 flex flex-col justify-between p-8 rounded card space-y-8">
              <div>
                <h3 className="text-2xl font-bold text-foreground mb-6">Luxe Salon</h3>
                
                <div className="space-y-6">
                  <div className="flex items-start gap-4">
                    <div className="p-3 rounded card text-foreground shrink-0 mt-0.5">
                      <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 10c0 6-8 12-8 12s-8-6-8-12a8 8 0 0 1 16 0Z"/><circle cx="12" cy="10" r="3"/></svg>
                    </div>
                    <div>
                      <p className="font-semibold text-foreground">Salon Location</p>
                      <p className="text-sm text-accent mt-0.5">458 Grand Avenue, Suite 200</p>
                      <p className="text-sm text-accent">Downtown Beverly Hills, CA 90210</p>
                    </div>
                  </div>

                  <div className="flex items-start gap-4">
                    <div className="p-3 rounded card text-foreground shrink-0 mt-0.5">
                      <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>
                    </div>
                    <div>
                      <p className="font-semibold text-foreground">Working Hours</p>
                      <p className="text-sm text-accent mt-0.5">Mon – Fri: 9:00 AM – 7:00 PM</p>
                      <p className="text-sm text-accent">Sat: 9:00 AM – 6:00 PM</p>
                      <p className="text-sm text-accent">Sun: Closed</p>
                    </div>
                  </div>

                  <div className="flex items-start gap-4">
                    <div className="p-3 rounded card text-foreground shrink-0 mt-0.5">
                      <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z"/></svg>
                    </div>
                    <div>
                      <p className="font-semibold text-foreground">Direct Contact</p>
                      <p className="text-sm text-accent mt-0.5">(555) 234-5678</p>
                      <p className="text-sm text-accent">appointments@luxesalon.com</p>
                    </div>
                  </div>
                </div>
              </div>

              <div className="pt-6 border-t border-accent/20 flex flex-wrap gap-3">
                <Button text={primaryButton.text} href={primaryButton.href} variant="primary" />
                <Button text={secondaryButton.text} href={secondaryButton.href} variant="secondary" />
              </div>
            </div>

            <div className="lg:col-span-7 rounded overflow-hidden card min-h-[400px] relative">
              <iframe
                title="Luxe Salon Location Map"
                src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3305.738878401311!2d-118.4003563234509!3d34.06334441714408!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x80c2bc04d6d147ab%3A0xd6c7c379fd381f!2sBeverly%20Hills%2C%20CA%2090210!5e0!3m2!1sen!2sus!4v1700000000000!5m2!1sen!2sus"
                width="100%"
                height="100%"
                style={{ border: 0, minHeight: '400px' }}
                allowFullScreen
                loading="lazy"
                referrerPolicy="no-referrer-when-downgrade"
                className="w-full h-full min-h-[400px]"
              />
            </div>
          </div>
        </ScrollReveal>
      </div>
    </section>
  );
};

export default function ContactSection() {
  return (
    <div data-webild-section="contact" data-section="contact" id="contact">
      <ContactInline />
    </div>
  );
}
