// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqSimple from '@/components/sections/faq/FaqSimple';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
            <SectionErrorBoundary name="faq">
              <FaqSimple
                tag="Questions?"
                title="Frequent Inquiries"
                description="Everything you need to know before your salon visit."
                items={[
                  { question: "What is your cancellation policy?", answer: "We require at least 24 hours notice for all cancellations to avoid a fee." },
                  { question: "Do you offer consultations?", answer: "Absolutely. We encourage consultations for all major transformations." },
                  { question: "Are your products cruelty-free?", answer: "Yes, we exclusively use premium cruelty-free products." },
                ]}
                textAnimation="slide-up"
              />
            </SectionErrorBoundary>
          </div>
  );
}
