// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "features" section.

import React from 'react';
import FeaturesRevealCards from '@/components/sections/features/FeaturesRevealCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FeaturesSection(): React.JSX.Element {
  return (
    <div id="features" data-section="features">
            <SectionErrorBoundary name="features">
              <FeaturesRevealCards
                tag="Our Expertise"
                title="Signature Hair Services"
                description="We blend artistic precision with premium hair care rituals."
                items={[
                  { title: "Hair Cut", description: "Bespoke color blending and expert highlights for a natural, healthy glow.", imageSrc: "https://storage.googleapis.com/webild/users/user_3FlzQsxiYdrM4aXHZmSOeQNKP1F/uploaded-1787196093627-ekvz5hht.jpg" },
                  { title: "Beard Trim", description: "Expert architectural cuts that frame your face and simplify your daily routine.", imageSrc: "https://storage.googleapis.com/webild/users/user_3FlzQsxiYdrM4aXHZmSOeQNKP1F/uploaded-1787196111261-fvjnnzzc.jpg" },
                  { title: "Hair Coloring", description: "Restorative hydration rituals that bring strength, shine, and vitality to your strands.", imageSrc: "https://images.pexels.com/photos/3993132/pexels-photo-3993132.jpeg?auto=compress&cs=tinysrgb&h=650&w=940&id=3993132" },
                ]}
                textAnimation="fade"
              />
            </SectionErrorBoundary>
          </div>
  );
}
