// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroTiltedCards from '@/components/sections/hero/HeroTiltedCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
            <SectionErrorBoundary name="hero">
              <HeroTiltedCards
                tag="Elevate Your Style"
                title="Professional Care for Exceptional Hair"
                description="Experience personalized styling and premium treatments in our serene, high-end studio."
                primaryButton={{
                  text: "Book Appointment",              href: "#contact"}}
                secondaryButton={{
                  text: "Our Services",              href: "#features"}}
                items={[
                  { imageSrc: "http://img.b2bpic.net/free-photo/back-view-female-tailor-working-studio_23-2148834097.jpg" },
                  { imageSrc: "http://img.b2bpic.net/free-photo/natural-elements-spa-with-beauty-cream_23-2148199484.jpg" },
                  { imageSrc: "http://img.b2bpic.net/free-photo/hairdresser-giving-hairstyle-young-woman_23-2147769862.jpg" },
                  { imageSrc: "http://img.b2bpic.net/free-photo/comb-brush-soap-cosmetic-jars-dark-background-space-text_185193-161817.jpg" },
                  { imageSrc: "http://img.b2bpic.net/free-photo/young-black-people-taking-care-afro-hair_23-2149575477.jpg" },
                ]}
                textAnimation="slide-up"
              />
            </SectionErrorBoundary>
          </div>
  );
}
