// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "metrics" section.

import React from 'react';
import MetricsIconCards from '@/components/sections/metrics/MetricsIconCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function MetricsSection(): React.JSX.Element {
  return (
    <div id="metrics" data-section="metrics">
            <SectionErrorBoundary name="metrics">
              <MetricsIconCards
                tag="By The Numbers"
                title="Our Legacy"
                description="A decade of making clients feel their most beautiful."
                metrics={[
                  { icon: "Sparkles", title: "Happy Clients", value: "15,000+" },
                  { icon: "Award", title: "Awards Won", value: "24" },
                  { icon: "Star", title: "Avg Rating", value: "4.9/5" },
                ]}
                textAnimation="slide-up"
              />
            </SectionErrorBoundary>
          </div>
  );
}
