// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "pricing" section.

import React from 'react';
import PricingCenteredCards from '@/components/sections/pricing/PricingCenteredCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function PricingSection(): React.JSX.Element {
  return (
    <div id="pricing" data-section="pricing">
            <SectionErrorBoundary name="pricing">
              <PricingCenteredCards
                tag="Investment"
                title="Simple Salon Pricing"
                description="Transparent pricing for high-end results."
                plans={[
                  { tag: "Essentials", price: "$400", description: "For standard maintenance and refresh.", features: ["Consultation", "Cut & Blow Dry", "Light Scalp Massage"], primaryButton: { text: "Book Now", href: "#contact" } },
                  { tag: "Signature", price: "$1000", description: "Our complete color & cut experience.", features: ["Full Color Consultation", "Highlight / Balayage", "Restorative Treatment"], primaryButton: { text: "Book Now", href: "#contact" } },
                  { tag: "Luxury", price: "$1800", description: "The ultimate transformation package.", features: ["Bespoke Coloring", "Precision Cut", "Luxury Keratin Treatment", "Gift Set"], primaryButton: { text: "Book Now", href: "#contact" } },
                ]}
                textAnimation="slide-up"
              />
            </SectionErrorBoundary>
          </div>
  );
}
