// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "team" section.

import React from 'react';
import TeamGlassCards from '@/components/sections/team/TeamGlassCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TeamSection(): React.JSX.Element {
  return (
    <div id="team" data-section="team">
            <SectionErrorBoundary name="team">
              <TeamGlassCards
                tag="The Artists"
                title="Meet Our Expert Stylists"
                description="Passionate professionals dedicated to your hair health."
                members={[
                  { name: "Sarah J.", role: "Lead Creative Director", imageSrc: "https://storage.googleapis.com/webild/users/user_3FlzQsxiYdrM4aXHZmSOeQNKP1F/uploaded-1786085320027-pwv2be6z.jpg" },
                  { name: "Julian D.", role: "Master Stylist", imageSrc: "https://images.pexels.com/photos/11018893/pexels-photo-11018893.jpeg?auto=compress&cs=tinysrgb&h=650&w=940&id=11018893" },
                  { name: "Mina K.", role: "Senior Colorist", imageSrc: "https://storage.googleapis.com/webild/users/user_3FlzQsxiYdrM4aXHZmSOeQNKP1F/uploaded-1786085388105-guwwn44x.jpg" },
                ]}
                textAnimation="fade-blur"
              />
            </SectionErrorBoundary>
          </div>
  );
}
