// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "team" section.

import React from 'react';
import TeamGlassCards from '@/components/sections/team/TeamGlassCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TeamSection(): React.JSX.Element {
  return (
    <div id="team" data-section="team">
            <SectionErrorBoundary name="team">
              <TeamGlassCards
                tag="The Artists"
                title="Meet Our Expert Stylists"
                description="Passionate professionals dedicated to your hair health."
                members={[
                  { name: "Sarah J.", role: "Lead Creative Director", imageSrc: "http://img.b2bpic.net/free-photo/confident-young-beautiful-female-barber-uniform-grabbed-hair-isolated-green-wall_141793-105669.jpg" },
                  { name: "Julian D.", role: "Master Stylist", imageSrc: "http://img.b2bpic.net/free-photo/man-sitting-chair-hairdresser-with-client-guy-drinkig-whiskey_1157-43567.jpg" },
                  { name: "Mina K.", role: "Senior Colorist", imageSrc: "http://img.b2bpic.net/free-photo/excited-young-beautiful-female-barber-uniform-holding-barber-tools-doing-beard-shaving-guy-isolated-pink-wall_141793-105761.jpg" },
                ]}
                textAnimation="fade-blur"
              />
            </SectionErrorBoundary>
          </div>
  );
}
