// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonial" section.

import React from 'react';
import TestimonialMarqueeOverlayCards from '@/components/sections/testimonial/TestimonialMarqueeOverlayCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialSection(): React.JSX.Element {
  return (
    <div id="testimonial" data-section="testimonial">
            <SectionErrorBoundary name="testimonial">
              <TestimonialMarqueeOverlayCards
                tag="Client Love"
                title="Loved by Our Community"
                description="Discover why our clients keep returning for our signature salon experience."
                testimonials={[
                  { name: "Clara S.", role: "Fashion Editor", company: "StyleDaily", rating: 5, imageSrc: "http://img.b2bpic.net/free-photo/woman-makeup-artist-looking-phone_23-2148332485.jpg" },
                  { name: "Mark D.", role: "Architect", company: "StudioArch", rating: 5, imageSrc: "http://img.b2bpic.net/free-photo/hairstyling-smiling-young-woman-demonstrating-hairstyling-tips_259150-60121.jpg" },
                  { name: "Elena V.", role: "Designer", company: "CreativeFlow", rating: 5, imageSrc: "http://img.b2bpic.net/free-photo/professional-girl-hairdresser-makes-client-haircut-girl-is-sitting-mask-beauty-salon_343596-4456.jpg" },
                  { name: "Sophie P.", role: "Executive", company: "TechInnovate", rating: 5, imageSrc: "http://img.b2bpic.net/free-photo/close-up-portrait-young-smiling-female_1301-109.jpg" },
                  { name: "James L.", role: "Photographer", company: "LensLife", rating: 5, imageSrc: "http://img.b2bpic.net/free-photo/closeup-beauty-woman-with-ideal-skin-looking-camera-grey-background_633478-648.jpg" },
                ]}
                textAnimation="fade-blur"
              />
            </SectionErrorBoundary>
          </div>
  );
}
